/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm") version "1.9.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.opencollab.dev/maven-snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.opencollab.dev/maven-releases/")
    }
    mavenCentral()
}

dependencies {
    compileOnly("cn.nukkit:nukkit:1.0-SNAPSHOT")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0")
}

group = "cn.nukkit"
version = "1.0.0"
description = "ExamplePlugin"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
