#name, main, version and api are required
name: ExamplePlugin
main: xyz.misilelaboratory.example
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.5"]
load: POSTWORLD
author: MisileLaboratory
description: Example plugin showing the API
website: https://github.com/misilelab/nukkit-plugin-template
#commands:
#  example:
#    description: Example command
#    usage: "/example"
#    aliases: ["xample", "nukkitexample"]
#    permission: exampleplugin.command.example
#    permission-message: "You do not have the required permission to run /example"
#permissions:
#  exampleplugin.command.example:
#    description: "Allows the user to run the example command"
#    default: true
##   children:
##     exampleplugin.command.example.test:
##       description: "Use the test feature in the example command"
##       default: true
